In [ ]:
# In

In [2]:
import pandas as pd 
arquivo = pd.read_csv('wine_dataset.csv')

In [6]:
arquivo

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,0
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,0
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,0
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [5]:
arquivo['style'] = arquivo['style'].replace('red',0) #o Valor red na coluna style recebe 0

In [8]:
arquivo['style'] = arquivo['style'].replace('white',1) # o Valor white na coluna style recebe 1

In [10]:
#Separando as variÃ¡veis entre preditoras e variÃ¡vel alvo
y = arquivo['style']
x = arquivo.drop('style', axis = 1) # x recebe tudo menos a coluna style, (axis = 1 Ã© coluna)

In [15]:
from sklearn.model_selection import train_test_split

#criando conjunto de dados de treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3) #Quero que 30% dos dados sejam para teste

In [19]:
from sklearn.ensemble import ExtraTreesClassifier
#CriaÃ§Ã£o de modelo
modelo = ExtraTreesClassifier()
modelo.fit(x_treino,y_treino)

#Imprimindo resultado
resultado = modelo.score(x_teste,y_teste)
print('AcurÃ¡cia: ', resultado)

AcurÃ¡cia:  0.9969230769230769

In [20]:
y_teste[400:404] #Amostra 400 a 4004

1572    0
3025    1
1914    1
4552    1
Name: style, dtype: int64

In [21]:
x_teste[400:404]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
1572,7.3,0.69,0.32,2.2,0.069,35.0,104.0,0.99632,3.33,0.51,9.5,5
3025,7.2,0.22,0.49,1.0,0.045,34.0,140.0,0.99000,3.05,0.34,12.7,6
1914,6.8,0.28,0.60,1.1,0.132,42.0,127.0,0.99340,3.09,0.44,9.1,6
4552,6.0,0.28,0.25,1.8,0.042,8.0,108.0,0.99290,3.08,0.55,9.0,5

In [22]:
previsoes = modelo.predict(x_teste[400:404])

In [23]:
previsoes

array([0, 1, 1, 1], dtype=int64)